//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.KuaidiDetail {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtFKuaiDiId;
		protected global::System.Web.UI.WebControls.TextBox txtFItemID;
		protected global::System.Web.UI.WebControls.TextBox txtFInterID;
		protected global::System.Web.UI.WebControls.TextBox txtFOrderInterID;
		protected global::System.Web.UI.WebControls.TextBox txtFCItemID;
		protected global::System.Web.UI.WebControls.TextBox txtFQty;
		protected global::System.Web.UI.WebControls.TextBox txtFSize;
		protected global::System.Web.UI.WebControls.TextBox txtFGrossWeight;
		protected global::System.Web.UI.WebControls.TextBox txtFSSize;
		protected global::System.Web.UI.WebControls.TextBox txtFSGrossWeight;
		protected global::System.Web.UI.WebControls.TextBox txtFMemo;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
