//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.KuaidiDetail {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblFKuaiDiId;
	protected global::System.Web.UI.WebControls.Label lblFItemID;
	protected global::System.Web.UI.WebControls.Label lblFInterID;
	protected global::System.Web.UI.WebControls.Label lblFOrderInterID;
	protected global::System.Web.UI.WebControls.Label lblFCItemID;
	protected global::System.Web.UI.WebControls.Label lblFQty;
	protected global::System.Web.UI.WebControls.Label lblFSize;
	protected global::System.Web.UI.WebControls.Label lblFGrossWeight;
	protected global::System.Web.UI.WebControls.Label lblFSSize;
	protected global::System.Web.UI.WebControls.Label lblFSGrossWeight;
	protected global::System.Web.UI.WebControls.Label lblFMemo;


       
    }
}
